### ISSUE TITLE
Add ruleset to prevent pushing to `main`

### ISSUE THREAD

**Issue by JakeLo123** [FusionAuth/fusionauth-javascript-sdk-express#2]
We should have a GitHub ruleset that blocks pushing to `main` branch. 
Creating a ruleset requires special permissions. I don’t have repo permissions to configure rulesets at the moment of writing this. 

To create a ruleset, go to Settings > rules/rulesets.

I would recommend this configuration:
- Ruleset Name: cannot-push-to-main
- Branch targeting criteria: include by pattern main
- Rules:
  - Require a pull request before merging with 1 required approval
  - Restrict deletions
  - Block force pushes

**Comment by mooreds** [comment]
Added ruleset per request.

**Comment by JakeLo123** [comment]
Thanks! Closing.
