### ISSUE TITLE
Revise README Documentation in JavaScript SDK Express

### ISSUE THREAD

**Issue by BriDavidson** [FusionAuth/fusionauth-javascript-sdk-express#3]
**Description**
The README documentation in the `javascript-sdk-express` repository needs revision to enhance readability, improve understanding, and eliminate any typos present. This update is to ensure that users can easily comprehend the instructions and information provided in the documentation. By revising the README, we aim to streamline the onboarding process for developers and enhance their overall experience with the SDK.

**Key Objectives**

1. Enhance understanding: Clarify ambiguous instructions and provide additional context where necessary to ensure users fully grasp the concepts presented.
2. Eliminate typos: Correct any spelling or grammatical errors to maintain professionalism and credibility in the documentation.

[Current README](https://github.com/FusionAuth/fusionauth-javascript-sdk-express/blob/main/README.md#example-server-implementation-for-fusionauth-web-sdks)

**Proposed README**

The edits to the introduction and set up of the repository improve the overall readability and understanding of the repository by removing typos, updating formatting of steps and explicitly stating the purpose, intended outcomes and intended use cases of the repository or FusionAuth SDKs.
```
Example: FusionAuth Web SDKs Server Implementation

This repository provides an example server implementation for [FusionAuth Web SDKs](https://github.com/FusionAuth/fusionauth-javascript-sdk). FusionAuth Web SDKs can be utilized in one of two ways:

1. Hosting Your Own Server: Implementing a server that handles OAuth token exchange and fulfills the [server code requirements for FusionAuth Web SDKs](https://github.com/FusionAuth/fusionauth-javascript-sdk-express#server-code-requirements).
2. Using the FusionAuth Hosted Server: Leveraging the server hosted on your FusionAuth instance, eliminating the need to write your own server code.

If you opt for hosting your own server, this repository will serve as an example. The provided example is in JavaScript and utilizes Express. If you opt to implement your own serve you are free to use any technology stack as long as it meets the server code requirements.

**Setup**
To get started, follow these steps:

1. From the root directory, run `npm install`.
2. Upon completion, run `npm run start`. 

You should observe the console output `FusionAuth example server listening on port 9000`.
```

Next we should add brief descriptions to each of the required endpoints listed, for example: 

```
**GET /app/me**
Description: Retrieves user information.
```

Lastly we should reformat this section to improve the readability:
```
GET /app/register
This endpoint is similar to /login. It must:

1. Generate PKCE code. 
a. The code verifier should be saved in a secure HTTP-only cookie. 
b. The code challenge is passed along
```

**Comment by JakeLo123** [comment]
Good feedback, thanks @BriDavidson
